import login from './login.js'
import signup from './signup.js'
import marketplace from './marketplace.js'
import cart from './cart.js'
import profile from './profile.js'
import orders from './orders.js'
import checkout from './checkout.js'
import forums from './forums.js'
import comment from './comment.js'
import user from './user.js'
import day from './day.js'
import task from './task.js'
import plant from './plant.js'
import chat from './chat.js'

export default [login, signup, marketplace, cart, profile, orders, checkout, forums, comment, user, day, task, plant, chat]